# fly.toml app configuration file generated for modern-python-demo on 2024-03-22T20:27:49+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'modern-python-demo'
primary_region = 'sin'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[checks]
[checks.health_check]
grace_period = "30s"
interval = "15s"
method = "get"
path = "/health"
port = 8000
timeout = "10s"
type = "http"
[checks.health_check.headers]
Content-Type = "application/json"
